In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
import cv2

In [2]:
model = load_model('train_model.h5')
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
cap = cv2.VideoCapture(0)
labels_dict={0:'MASK',1:'NO MASK'}
color_dict={0:(0,255,0),1:(0,0,255)}

In [3]:
while True:
    ret,image = cap.read()
    faces = face_cascade.detectMultiScale(image,1.1,4)
    print(faces)
    print('dont come here')
    for (x,y,w,h) in faces:
        
        face_img = image[y:y+w,x:x+w]
        resized = cv2.resize(face_img,(100,100))
        normalized = resized/255
        print(normalized.shape)
        normalized = np.reshape(normalized,(1,100,100,3))
        result = model.predict(normalized)
        result = result>0.5
        if(result):
          result=1
        else:
            result=0
        cv2.rectangle(image,(x,y),(x+w,y+h),color_dict[result],2)
        cv2.rectangle(image,(x,y-40),(x+w,y),color_dict[result],-1)
        cv2.putText(image, labels_dict[result], (x, y-10),cv2.FONT_HERSHEY_SIMPLEX,0.8,(255,255,255),2)
        print('come here')
    
    cv2.imshow('live',image)
    if cv2.waitKey(1) & 0xff==ord('q'):
        break

cv2.destroyAllWindows()
cap.release()

[[282  86 139 139]]
dont come here
(100, 100, 3)
come here
[[287  88 132 132]]
dont come here
(100, 100, 3)
come here
[[289  87 132 132]]
dont come here
(100, 100, 3)
come here
[[289  85 134 134]]
dont come here
(100, 100, 3)
come here
[[289  83 132 132]]
dont come here
(100, 100, 3)
come here
[[273  97 126 126]]
dont come here
(100, 100, 3)
come here
[[273  93 131 131]]
dont come here
(100, 100, 3)
come here
[[273  93 130 130]]
dont come here
(100, 100, 3)
come here
[[278  96 122 122]]
dont come here
(100, 100, 3)
come here
[[276 101 124 124]]
dont come here
(100, 100, 3)
come here
[[278 102 121 121]]
dont come here
(100, 100, 3)
come here
[[277 103 124 124]]
dont come here
(100, 100, 3)
come here
[[274 103 128 128]]
dont come here
(100, 100, 3)
come here
[[272 101 133 133]]
dont come here
(100, 100, 3)
come here
[[272 101 134 134]]
dont come here
(100, 100, 3)
come here
[[273 102 133 133]]
dont come here
(100, 100, 3)
come here
[[274 105 136 136]]
dont come here
(100, 100, 3)
come he

()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
[[456 229  35  35]]
dont come here
(100, 100, 3)
come here
()
dont come here
[[286 212  85  85]]
dont come here
(100, 100, 3)
come here
[[370 226  63  63]]
dont come here
(100, 100, 3)
come here
[[341 180 141 141]]
dont come here
(100, 100, 3)
come here
()
dont come here
()
dont come here
()
dont come here
[[317 194 179 179]]
dont come here
(100, 100, 3)
come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
[[437 160  58  58]]
dont come here
(100

come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
[[419  28  31  31]]
dont come here
(100, 100, 3)
come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
[[266 152 162 162]]
dont come here
(100, 100, 3)
come here
()
dont come here
()
dont come here
()
dont come here
[[266 15

()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
[[159 292  28  28]]
dont come here
(100, 100, 3)
come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
[[158 293  28  28]]
dont come here
(100, 100, 3)
come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here


[[258 127 166 166]]
dont come here
(100, 100, 3)
come here
[[253 125 172 172]]
dont come here
(100, 100, 3)
come here
[[257 128 171 171]]
dont come here
(100, 100, 3)
come here
[[256 130 168 168]]
dont come here
(100, 100, 3)
come here
[[259 131 167 167]]
dont come here
(100, 100, 3)
come here
[[259 133 165 165]]
dont come here
(100, 100, 3)
come here
[[265 139 156 156]]
dont come here
(100, 100, 3)
come here
[[266 140 153 153]]
dont come here
(100, 100, 3)
come here
[[268 141 147 147]]
dont come here
(100, 100, 3)
come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
(

[[254 129 168 168]]
dont come here
(100, 100, 3)
come here
[[249 126 175 175]]
dont come here
(100, 100, 3)
come here
[[252 128 169 169]]
dont come here
(100, 100, 3)
come here
[[249 126 176 176]]
dont come here
(100, 100, 3)
come here
[[254 130 168 168]]
dont come here
(100, 100, 3)
come here
[[251 132 171 171]]
dont come here
(100, 100, 3)
come here
[[251 137 174 174]]
dont come here
(100, 100, 3)
come here
[[252 141 174 174]]
dont come here
(100, 100, 3)
come here
[[252 145 168 168]]
dont come here
(100, 100, 3)
come here
[[260 148 158 158]]
dont come here
(100, 100, 3)
come here
()
dont come here
[[265 153 144 144]]
dont come here
(100, 100, 3)
come here
[[265 147 150 150]]
dont come here
(100, 100, 3)
come here
()
dont come here
[[256 142 161 161]]
dont come here
(100, 100, 3)
come here
[[258 146 154 154]]
dont come here
(100, 100, 3)
come here
[[255 139 164 164]]
dont come here
(100, 100, 3)
come here
[[251 135 173 173]]
dont come here
(100, 100, 3)
come here
[[250 134 171 171]]


come here
[[264 140 162 162]]
dont come here
(100, 100, 3)
come here
[[279 143 158 158]
 [185 163 261 261]]
dont come here
(100, 100, 3)
come here
(100, 100, 3)
come here
[[290 149 150 150]]
dont come here
(100, 100, 3)
come here
[[322 230  59  59]]
dont come here
(100, 100, 3)
come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont c

()
dont come here
()
dont come here
()
dont come here
()
dont come here
[[339 286  77  77]]
dont come here
(100, 100, 3)
come here
()
dont come here
()
dont come here
()
dont come here
[[289  57 146 146]]
dont come here
(100, 100, 3)
come here
[[290  61 143 143]]
dont come here
(100, 100, 3)
come here
[[289  60 146 146]]
dont come here
(100, 100, 3)
come here
[[293  63 138 138]]
dont come here
(100, 100, 3)
come here
[[286  56 147 147]]
dont come here
(100, 100, 3)
come here
[[288  57 145 145]]
dont come here
(100, 100, 3)
come here
[[290  58 140 140]]
dont come here
(100, 100, 3)
come here
[[291  61 138 138]]
dont come here
(100, 100, 3)
come here
[[291  58 142 142]]
dont come here
(100, 100, 3)
come here
[[288  56 147 147]]
dont come here
(100, 100, 3)
come here
[[290  56 144 144]]
dont come here
(100, 100, 3)
come here
[[288  57 142 142]]
dont come here
(100, 100, 3)
come here
[[289  57 141 141]]
dont come here
(100, 100, 3)
come here
[[288  54 145 145]]
dont come here
(100, 100, 3)

()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont co

()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
[[289 268  50  50]]
dont come here
(100, 100, 3)
come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
[[471   2  49  49]]
dont come here
(100, 100, 3)
come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
[[128 333  51  51]]
dont come here
(100, 100, 3)
come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
[[431  72  45  45]]
dont come here
(100, 100, 3)
come here
()
dont come here
()
dont 

()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
[[287 285  55  55]]
dont come here
(100, 100, 3)
come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
[[138 308  56  56]]
dont come here
(100, 100, 3)
come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
[[134 305  57  57]]
dont come here
(100, 100, 3)
come 

come here
[[302 131 126 126]]
dont come here
(100, 100, 3)
come here
[[303 130 126 126]]
dont come here
(100, 100, 3)
come here
[[304 130 130 130]]
dont come here
(100, 100, 3)
come here
[[306 131 127 127]]
dont come here
(100, 100, 3)
come here
[[305 131 126 126]]
dont come here
(100, 100, 3)
come here
[[305 131 125 125]]
dont come here
(100, 100, 3)
come here
[[302 130 128 128]]
dont come here
(100, 100, 3)
come here
[[304 134 120 120]]
dont come here
(100, 100, 3)
come here
[[305 133 120 120]]
dont come here
(100, 100, 3)
come here
[[304 131 125 125]]
dont come here
(100, 100, 3)
come here
[[310 130 125 125]]
dont come here
(100, 100, 3)
come here
[[316 129 130 130]]
dont come here
(100, 100, 3)
come here
[[315 117 143 143]]
dont come here
(100, 100, 3)
come here
[[310 102 151 151]]
dont come here
(100, 100, 3)
come here
[[299  96 155 155]]
dont come here
(100, 100, 3)
come here
[[294 117 137 137]]
dont come here
(100, 100, 3)
come here
[[282 121 143 143]]
dont come here
(100, 100, 

()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont co

()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont come here
()
dont co

In [11]:
cap.release()